
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "default";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames = "article" | "event" | "landing_page" | "solution" | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames = "default";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "default";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames = "event_topic" | "event_type";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = "archived" | "draft" | "published" | "scheduled";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "autoplay"
  | "body_copy"
  | "caption"
  | "description"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "headline"
  | "hero_image"
  | "image"
  | "introduction"
  | "name"
  | "publish_date"
  | "start_date"
  | "subheadline"
  | "title"
  | "video_link";
