
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Event Topic
 *
 * Codename: event_topic
 * Id: c73d35c2-df63-53f5-a9e5-a8450b027704
 */
export const eventTopicValues = ["nutrition", "physical_fitness", "preventative_care"] as const;

/**
 * Type representing Event Topic taxonomy
 *
 * Codename: event_topic
 * Id: c73d35c2-df63-53f5-a9e5-a8450b027704
 */
export type EventTopic = (typeof eventTopicValues)[number];

/**
 * Type guard for Event Topic
 *
 * Codename: event_topic
 * Id: c73d35c2-df63-53f5-a9e5-a8450b027704
 */
export function isEventTopic(value: string | undefined | null): value is EventTopic {
  return typeof value === "string" && (eventTopicValues as readonly string[]).includes(value);
}
