
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export type Article = CoreContentType<
  ArticleElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc
     */
    readonly title: Elements.TextElement;
    /**
     * Introduction
     *
     * Type: text
     * Required: true
     * Codename: introduction
     * Id: c3fc1a88-5577-5130-b0aa-b1837c009ba6
     */
    readonly introduction: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 8c501358-d0f7-5959-95bd-2991f1215e33
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: true
     * Codename: body_copy
     * Id: 0747fb13-7383-59fe-bf64-2bab6d384279
     */
    readonly body_copy: Elements.RichTextElement<CoreContentType>;
    /**
     * Publish Date
     *
     * Type: date_time
     * Required: true
     * Codename: publish_date
     * Id: abdf08ea-55f0-5460-96e0-391f7471c7e9
     */
    readonly publish_date: Elements.DateTimeElement;
  },
  "article"
>;

/**
 * Type representing all available element codenames for Article
 */
export type ArticleElementCodenames = "title" | "introduction" | "image" | "body_copy" | "publish_date";

/**
 * Type guard for Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export function isArticle(item: CoreContentType | undefined | null): item is Article {
  return item?.system?.type === "article";
}
