
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Video, Event, Article } from "./index.ts";

/**
 * Landing Page
 *
 * Id: aa610b72-ca00-5ee3-bd30-f5b001b9d64e
 * Codename: landing_page
 */
export type LandingPage = CoreContentType<
  LandingPageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: ff2c9d21-64f1-5d64-b650-344dd0ba44d2
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: 96fa63e6-2f46-557d-9dc8-4874ae9340a6
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: true
     * Codename: hero_image
     * Id: efe09118-3de6-5581-b784-43408e2e673b
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: false
     * Codename: body_copy
     * Id: b0e94942-8d23-5f67-aa72-15c0ed45a390
     */
    readonly body_copy: Elements.RichTextElement<Video>;
    /**
     * Featured Content
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_content
     * Id: 7f939caa-a3a2-5018-a127-fe2938129fa9
     */
    readonly featured_content: Elements.LinkedItemsElement<Event | Article>;
  },
  "landing_page"
>;

/**
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageElementCodenames = "headline" | "subheadline" | "hero_image" | "body_copy" | "featured_content";

/**
 * Type guard for Landing Page
 *
 * Id: aa610b72-ca00-5ee3-bd30-f5b001b9d64e
 * Codename: landing_page
 */
export function isLandingPage(item: CoreContentType | undefined | null): item is LandingPage {
  return item?.system?.type === "landing_page";
}
