
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Solution
 *
 * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
 * Codename: solution
 */
export type Solution = CoreContentType<
  SolutionElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 9148131a-90f6-588a-bea4-c0397dbc554b
     */
    readonly headline: Elements.TextElement;
    /**
     * Introduction
     *
     * Type: text
     * Required: true
     * Codename: introduction
     * Id: ec1fba9b-f3ed-5653-ac01-9815dca28b61
     */
    readonly introduction: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 481aa452-c113-5bb1-ae61-21b112bd0841
     */
    readonly image: Elements.AssetsElement;
  },
  "solution"
>;

/**
 * Type representing all available element codenames for Solution
 */
export type SolutionElementCodenames = "headline" | "introduction" | "image";

/**
 * Type guard for Solution
 *
 * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
 * Codename: solution
 */
export function isSolution(item: CoreContentType | undefined | null): item is Solution {
  return item?.system?.type === "solution";
}
