
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-19'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Developer Completed
* Id: 133f5ef8-66b1-0074-7d42-55371447aac4
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Video
 *
 * Id: 5b2003c5-fe38-5a6e-a21b-a7b2f5ee0ddb
 * Codename: video
 */
export type Video = CoreContentType<
  VideoElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: false
     * Codename: headline
     * Id: 0bd216b2-4975-50f9-832e-6e2c6c5d1bf9
     */
    readonly headline: Elements.TextElement;
    /**
     * Description
     *
     * Type: text
     * Required: false
     * Codename: description
     * Id: c454e463-2c85-57a2-aec8-e399a392b229
     */
    readonly description: Elements.TextElement;
    /**
     * Video Link
     *
     * Type: text
     * Required: true
     * Codename: video_link
     * Id: 09573446-747b-572e-af77-9cbf359bcdad
     */
    readonly video_link: Elements.TextElement;
    /**
     * Caption
     *
     * Type: text
     * Required: false
     * Codename: caption
     * Id: c3054bab-604f-5d9d-bf1f-06c87cd5b15e
     */
    readonly caption: Elements.TextElement;
    /**
     * Autoplay
     *
     * Type: multiple_choice
     * Required: false
     * Codename: autoplay
     * Id: 21250a1b-2eff-52cc-89b2-a44a2bab8b93
     */
    readonly autoplay: Elements.MultipleChoiceElement<"true" | "false">;
  },
  "video"
>;

/**
 * Type representing all available element codenames for Video
 */
export type VideoElementCodenames = "headline" | "description" | "video_link" | "caption" | "autoplay";

/**
 * Type guard for Video
 *
 * Id: 5b2003c5-fe38-5a6e-a21b-a7b2f5ee0ddb
 * Codename: video
 */
export function isVideo(item: CoreContentType | undefined | null): item is Video {
  return item?.system?.type === "video";
}
